# Generated by Django 5.1.3 on 2024-12-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('testimonial_text', models.TextField()),
            ],
        ),
    ]
