# Generated by Django 5.1.3 on 2024-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
